How#Failed to start bean 'documentationPluginsBootstrapper'; nested exception is java.lang.NullPointerException
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER
springfox.documentation.auto-startup=false

server.port:8080
server.address=0.0.0.0

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# http Settings
http.connection.timeoutInMS=5000
endpoint.accountBalance=http://localhost:8080/mybank/v1/account/{accountId}/balance

# actuator 
management.endpoints.web.exposure.include=loggers
management.endpoint.loggers.enabled=true

